[build]
  command = "npm install && cd netlify/functions && npm install && cd ../.. && npm run build"
  publish = "build"
  functions = "netlify/functions"

[functions]
  timeout = 26

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
